---
- name: Install Docker and Docker Compose on Linux
  hosts: tf_deployed_vm
  become: yes

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    docker_compose_version: "1.29.2"
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose (standalone binary)
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: "{{ docker_compose_path }}"
        mode: '0755'
      when: docker_compose_version is defined and docker_compose_version != ''

    - name: Verify docker-compose version
      command: "{{ docker_compose_path }} --version"
      register: compose_version_output
      changed_when: false

    - name: Show docker-compose version
      debug:
        msg: "{{ compose_version_output.stdout }}"

