name: homelab-automation

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install_software:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container:
      image: alpine:3.22
    steps:
     - uses: actions/checkout@v4
     - name: Install required software
       run: | 
           apk update
           apk add --no-cache curl ansible openssh
           curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
           chmod 700 install-opentofu.sh
           ./install-opentofu.sh --install-method apk
           rm -f install-opentofu.sh
     
     - uses: actions/checkout@v4
     - name: Run Terraform
       run: |
          tofu init
          tofu apply --auto-approve
